#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.03 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffff;
constexpr uint24_t FX_DATA_BYTES = 86;

constexpr uint24_t fromSD = 0x000000;
